version: '3.8'

services:
  scheduler:
    build:
      context: .
      dockerfile: services/parser/Dockerfile
    container_name: news_graph_scheduler
    volumes:
      - ./logs:/app/logs
      - ./config/schedule_config.yaml:/app/config/schedule_config.yaml
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - news_network

  summarizer:
    build:
      context: .
      dockerfile: services/summarizer/Dockerfile
    container_name: news_graph_summarizer
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - news_network

  ner:
    build:
      context: .
      dockerfile: services/ner/Dockerfile
    container_name: news_graph_ner
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - news_network

  bot:
    build:
      context: .
      dockerfile: services/bot/Dockerfile
    container_name: news_graph_bot
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - news_network

networks:
  news_network:
    driver: bridge