# pg_hba.conf
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    all             all             0.0.0.0/0               md5  # Внешний доступ с MD5 паролем
# Локальный доступ
local   all             all                                     trust
host    all             all             127.0.0.1/32            md5