lenta_hourly:
  enabled: true
  cron: "15,45 * * * *"
  kwargs:
    categories: "Россия,Бывший СССР,Политика,Экономика,Мир,Наука и техника,Интернет и СМИ"
    limit: 50
tinvest_hourly:
  enabled: true
  cron: "0,30 * * * *"
  kwargs:
    tickers: "SBER,VTBR,GAZP,LKOH,GMKN,NVTK,TATN,ROSN,ALRS,MOEX,YDEX,OZON,AFKS,PHOR,MGNT"
    limit: 50
